### ISSUE TITLE
https://registry.yarnpkg.com/@expo-google-fonts%2fnoto-serif-jp: Not found

### ISSUE THREAD

**Issue by markymc** [expo/google-fonts#10]
Hi,

I'm trying to install https://github.com/expo/google-fonts/tree/master/font-packages/noto-serif-jp as per the instructions `expo install @expo-google-fonts/noto-serif-jp expo-font` and I'm getting the following error:

```
> yarn add @expo-google-fonts/noto-serif-jp expo-font@~8.1.0
yarn add v1.19.2
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo-google-fonts%2fnoto-serif-jp: Not found".
```

I looked on npm at https://www.npmjs.com/package/@expo-google-fonts/noto-serif-jp and it's not there. https://www.npmjs.com/package/@expo-google-fonts/noto-serif is there of course.

Is this intended?

Thanks!

**Comment by ccheever** [comment]
I've updated all the packages and republished them. 
I tried doing an `expo install @expo-google-fonts/noto-serif-jp` and it worked so I think this issue should be resolved now. Sorry for the trouble.

**Comment by markymc** [comment]
Thanks @ccheever!
