### ISSUE TITLE
Space Mono seems not to install correctly

### ISSUE THREAD

**Issue by wlycdgr** [expo/google-fonts#12]
(Expo SDK 38 and 39)
(Windows 10 Pro, PowerShell, Node v12.18.4, Yarn)

When I install Space Mono using `expo install @expo-google-fonts/space-mono`, the actual `ttf` files and the `index.js` file are not installed. Noticed this when Metro bundler failed out while trying to bundle up a dev build for my Android, because it couldn't find the module's `index.js` file.

I tried to rep this with three other font packages (Sofia, Sarala, and Tenor Sans) and could not. All installed their `ttf` files and `index.js` files as expected.

**Comment by haneenmahd** [comment]
I could install it for my project.
The better way to use is that put the font File in your assets folder of your project.
And then Cached Resources to require it as a module.

**Comment by ccheever** [comment]
Hi - I couldn't reproduce this.
Here is an example project where it is working.
https://github.com/ccheever/test-space-mono
