### ISSUE TITLE
Font Sora not found

### ISSUE THREAD

**Issue by bceppi** [expo/google-fonts#14]
Hi! Thanks for all the work and the available Fonts.

I wanted to warn that the font Sora is not available, so everybody can know.

I'll try to contribute but I'm not available in the short term.

**Comment by lakmalmabm** [comment]
Thanks man.. you saved my life 🤟

**Comment by ccheever** [comment]
I've updated the fonts to include the latest fonts newly added to Google Fonts, including Sora.
Here is the Sora package: https://www.npmjs.com/package/@expo-google-fonts/sora
