### ISSUE TITLE
woff2 and woff variants

### ISSUE THREAD

**Issue by DanielRuf** [expo/google-fonts#2]
In general woff2 and woff are much better and can be better compressed for web.

I think there is some overlapping with what https://github.com/KyleAMathews/typefaces already does but with a smaller set of font files.

Wouldn't this work for expo projects too?

**Comment by ccheever** [comment]
Some relevant discussion on Twitter here: https://twitter.com/DanielRufde/status/1261049162906456068?s=20

**Comment by ccheever** [comment]
I think in general this should be doable but one thing that is tricky is that woff files often use different font files for different unicode ranges. Ex. Look at this CSS from the Google Fonts API : https://fonts.googleapis.com/css2?family=Crimson+Pro . It has 3 different woff2 files -- one for Vietnamese, one for Latin-ext, and one for Latin. I can imagine a way to implement something in JS where a Text element is broken into smaller text elements based on the unicode ranges of the characters it contains, but I think that would net out being less performant than just using the TTF.

**Comment by DanielRuf** [comment]
> I think in general this should be doable but one thing that is tricky is that woff files often use different font files for different unicode ranges.

In most cases users know what languages and ranges they need. Or do you mean some way to automize and simplify this?

**Comment by ccheever** [comment]
If you have any ideas about how to approach this, please share here
