### ISSUE TITLE
Epilogue Font Import: Not Supported

### ISSUE THREAD

**Issue by azzageee** [expo/google-fonts#24]
Maybe I am mistaken,

But does this package not support import of Epilogue font? 

https://fonts.google.com/specimen/Epilogue?query=epilo

Thanks in advance.

**Comment by ccheever** [comment]
I've updated the packages to include newer fonts added to Google Fonts recently.
Here is Epilogue: https://github.com/expo/google-fonts/tree/master/font-packages/epilogue#readme
