### ISSUE TITLE
Can you expose this as a npm package for each unique font?

### ISSUE THREAD

**Issue by niftylettuce** [expo/google-fonts#3]
If you wrote an automated build that published these as scoped fonts, that would be incredible, and I would gladly donate for this.

**Comment by ccheever** [comment]
@niftylettuce Isn't there an npm package for each font? Ex. https://www.npmjs.com/package/@expo-google-fonts/nunito-sans

Or do you mean something else?

**Comment by niftylettuce** [comment]
Oh this is awesome.  This is exactly what I needed.  Thanks Charlie!

**Comment by niftylettuce** [comment]
FYI going to be used on https://forwardemail.net
