### ISSUE TITLE
useFonts not loading Poppins_600SemiBold on iOS 15, dev beta 4

### ISSUE THREAD

**Issue by programmrz** [expo/google-fonts#39]
When I attempt to load Poppins_600SemiBold, the async function never completes. Can consistently reproduce on iOS 15 beta 15. Doesnt complete or error out

`
var [fontsLoaded] = useFonts({
    
    Poppins_400Regular,
    Poppins_700Bold,
    Poppins_500Medium,
    Poppins_600SemiBold
  })

  if (!fontsLoaded) {
    return <AppLoading />;
  }
  return (
    <NavigationContainer>
      <StatusBar
        animated={true}
        backgroundColor="#87ceeb"
        barStyle={statusBarStyle}
        showHideTransition={statusBarTransition}
        hidden={hidden} />
      <Main />
    </NavigationContainer>
  );`

**Comment by ccheever** [comment]
Does this only happen on iOS 15 or does it happen on other iOS versions as well?

**Comment by ccheever** [comment]
The example code works just fine for me on iOS 14 so maybe it's an iOS 15 problem. 
Please post a complete working example if so.

**Comment by programmrz** [comment]
After alot of digging, it appears it's an Expo Go issue when downloading Fonts via LAN. asset.downloadAsync(); in FontLoader.js intermittently never returns which in turn never calls back to fontsLoading. I still dont know why another project using the same fonts work. I'm just happy I "resolved" my issue

**Comment by fredrivett** [comment]
Thanks @programmrz for your thread and following up with the answer here. Likewise for me I was unable to download fonts via LAN on my parents home wifi network whilst visiting, but when switching to tethering they downloaded as expected.

I'm using an EAS built client (using `eas build --platform ios --profile dev`) so this isn't just an Expo Go issue. My parents have relatively strict parental controls, so it wouldn't surprise me if something was getting blocked that Expo relies upon.

**Comment by ccheever** [comment]
FYI - If you install the font packages in an app and build it and put it in the App Store, they will be actually embedded in the binary, and so your users won't be affected by this. 

If anyone finds out more about the situations where these fonts can't load, let me know. It's hard for me to debug this because I can't reproduce the problem. Thanks for the info everyone who has shared stuff here.
