### ISSUE TITLE
useFonts returns false after switching expo-cli from 3.21.12 to 3.22.0

### ISSUE THREAD

**Issue by titoasty** [expo/google-fonts#4]
Hi,

After switching expo-cli from 3.21.12 to 3.22.0, useFonts returns true with the fonts specified (tried with nunito).
Downgrading to 3.21.12 works.

I don't know if it's related to expo-fonts or expo-cli?

Edit: replaced "true" to "false" in title

**Comment by HarrisonJackson** [comment]
We ran into this issue: https://github.com/expo/expo/issues/9135 and the only way we could get this google-fonts wrapper to work was by downgrading expo as mentioned by @titoasty above.

```

**Comment by Albert-Gao** [comment]
Downgrade `expo-cli` to `3.21.13`, it works now. seems like related to `expo-cli`

**Comment by Albert-Gao** [comment]
Try the new expo-cli@3.22.1 It's working now!

**Comment by titoasty** [comment]
Working in 3.22.1!
Thanks, closing now!

**Comment by OrganicCoder** [comment]
Hmm I upgraded to 3.22.1 but getting "Invariant Violation: Invalid prop 'fontFamily' of type 'number' supplied to 'StyleSheet....". I'm using expo version 38.0.8 and expo-font version 8.2.1. Something's not right after upgrading.
