### ISSUE TITLE
Is Urbanist Font available ?

### ISSUE THREAD

**Issue by julien040** [expo/google-fonts#51]
Hi,
I can't find the [Urbanist font](https://fonts.google.com/specimen/Urbanist).

**Comment by ccheever** [comment]
It may be a new font recently added to Google Fonts if you can't find it. 

I'll make a new release soon which will pull in all the fonts.
In the meantime, you could try running the script to generate the packages yourself; or just wait for me to do it.

Charlie

**Comment by demonDragon12** [comment]
what!?

**Comment by demonDragon12** [comment]
@julien040 dats crazty

**Comment by ccheever** [comment]
Available here now. https://www.npmjs.com/package/@expo-google-fonts/urbanist
Closing
