### ISSUE TITLE
Add Zen Kaku font

### ISSUE THREAD

**Issue by douardo** [expo/google-fonts#54]
Would it be possible to add the Zen Kaku Gothic Antique Google Font?

https://fonts.google.com/specimen/Zen+Kaku+Gothic+Antique

Thanks.

**Comment by ccheever** [comment]
I'll do another release soon which should capture all the new fonts added to Google Fonts, like this one.

In the meantime, you could try following the instructions for generating packages yourself. Or just wait for me to do it.

**Comment by ccheever** [comment]
https://www.npmjs.com/package/@expo-google-fonts/zen-kaku-gothic-antique
